DROP TABLE IF EXISTS apartment;

DROP TABLE IF EXISTS user_apartment_wishlist;

DROP TABLE IF EXISTS worksite;

DROP TABLE IF EXISTS user;

DROP TABLE IF EXISTS landlord;

DROP TABLE IF EXISTS floor_plan;

DROP TABLE IF EXISTS price_plan;

DROP TABLE IF EXISTS floor_plan_price;

DROP TABLE IF EXISTS restaurant;

DROP TABLE IF EXISTS plaza;

DROP TABLE IF EXISTS grocery;

DROP TABLE IF EXISTS park;
